CREATE TABLE Teams (
    team_id NUMBER PRIMARY KEY,
    team VARCHAR2(100) NOT NULL,
    country VARCHAR2(50),
    logo VARCHAR2(100)
);

CREATE TABLE Players (
    player_id NUMBER PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    nationality VARCHAR2(30 ),
    field_position VARCHAR2(30),
    position VARCHAR2(30),
    weight NUMBER,
    height NUMBER,
    age NUMBER,
    player_image VARCHAR2(100),
    team_id NUMBER NOT NULL,
    CONSTRAINT fk_team FOREIGN KEY (team_id) REFERENCES Teams(team_id) ON DELETE CASCADE
);

CREATE TABLE Goals (
    goals_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player_id NUMBER NOT NULL,
    inside_area NUMBER,
    outside_area NUMBER,
    right_foot NUMBER,
    left_foot NUMBER,
    head NUMBER,
    other NUMBER,
    penalties_scored NUMBER,
    goals_scored NUMBER DEFAULT 0,
    CONSTRAINT fk_player_goals FOREIGN KEY (player_id) REFERENCES Players(player_id) ON DELETE CASCADE
);

CREATE TABLE Goalkeeping (
    goalkeeping_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player_id NUMBER NOT NULL,
    saves NUMBER,
    goals_conceded NUMBER,
    saves_on_penalty NUMBER,
    clean_sheets NUMBER,
    punches_made NUMBER,
    CONSTRAINT fk_player_goalkeeping FOREIGN KEY (player_id) REFERENCES Players(player_id) ON DELETE CASCADE
);

CREATE TABLE Attacking (
    attacking_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player_id NUMBER NOT NULL,
    assists NUMBER,
    corners_taken NUMBER,
    offsides NUMBER,
    dribbles NUMBER,
    CONSTRAINT fk_player_attacking FOREIGN KEY (player_id) REFERENCES Players(player_id) ON DELETE CASCADE
);

CREATE TABLE Defending (
    defending_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player_id NUMBER NOT NULL,
    balls_recovered NUMBER,
    tackles NUMBER,
    tackles_won NUMBER,
    tackles_lost NUMBER,
    clearance_attempted NUMBER,
    CONSTRAINT fk_player_defending FOREIGN KEY (player_id) REFERENCES Players(player_id) ON DELETE CASCADE
);


